# Site
title: Dwarak
baseurl: ""
url: "https://dwarak.in"

# User's social address
social:
  twitter_username: dtsdwarak
  gplus_name: DwarakaNath
  linkedin_username: dtsdwarak
  github_username:  dtsdwarak
  blog_link: https://blog.dwarak.in
  resume_link: https://dwrk.in/drive_resume
  email_address: me-@-dwarak.in

# Bio
user:
  name: "Dwarak"
  description: Code. Life. Fun.
  about: "20 something software engineer. Mozzie of Madras. 
          Square eyes. Shortcut show-off. Sluggard. Lousy singer. 
          Alan of my wolfpack. Blogs and codes by interest."
  place: "Chennai, India"
  image_link: "https://lh6.googleusercontent.com/1LfMDGZU8C0H4OqMD_lQVClmVFu45r83W4FIWt2GkbbenfTDKkNd_GqZR_IH2swjTYuuEf6I=w1366-h652-rw" 

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
